version: '3'

# builds the api container and sets up the localstack container to run

services:
  angular-docker:
    build: .
    ports:
      - '4200:4200'
      - '49153:49153'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    container_name:  angular-docker
    depends_on: 
      - mysql
      - redis
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    expose:
      - 3306
    container_name: angular-mysql

  redis:
    image: redis
    restart: always
    container_name: angular-redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    